Repository cbslneu/heartview, pull requests merged in 2025-07, with the labels that each got.

#16 [BE-4] Inconsistent beat rendering and signal label in legend
  beat-editor/src/components/BeatChart.js
  beat-editor/src/components/ChartOptions.js
  beat-editor/src/hooks/useChartZoom.js
Labels: bug

#25 [DOCS-1] Add Zoom + Panning section and their keyboard shortcuts
  docs/beat-editor-getting-started.rst
  docs/beat-editor-quick-guide.rst
Labels: documentation

#26 [BE-6] Create Keyboard Shortcuts Tooltip
  beat-editor/src/components/BeatChart/BeatChart.jsx
  beat-editor/src/components/KeyboardShortcuts/KeyboardShortcuts.jsx
  beat-editor/src/styles.scss
Labels: enhancement
