Repository cbslneu/heartview, pull requests merged in 2025-08, with the labels that each got.

#36 BE-8: Migrated create-react-app to Vite and Node 20 to 22
  beat-editor/README.md
  beat-editor/index.html
  beat-editor/package-lock.json
  beat-editor/package.json
  beat-editor/public/fonts/Poppins-Bold.ttf
  beat-editor/public/fonts/Poppins-Bold.woff
  beat-editor/public/fonts/Poppins-Bold.woff2
  beat-editor/public/fonts/Poppins-Italic.ttf
  beat-editor/public/fonts/Poppins-Italic.woff
  beat-editor/public/fonts/Poppins-Italic.woff2
  beat-editor/public/fonts/Poppins-Regular.ttf
  beat-editor/public/fonts/Poppins-Regular.woff
  beat-editor/public/fonts/Poppins-Regular.woff2
  beat-editor/public/index.html
  beat-editor/public/manifest.json
  beat-editor/public/robots.txt
  beat-editor/server/app.js
  beat-editor/src/App.jsx
  beat-editor/src/components/BeatChart/BeatChart.jsx
  beat-editor/src/components/BeatChart/BeatChartContainer.jsx
  beat-editor/src/index.jsx
  beat-editor/src/styles.scss
  beat-editor/vite.config.js
Labels: maintenance

#40 BE-12: Developed alternative solution for panning and mark unusable
  beat-editor/.gitignore
  beat-editor/frontend/hooks/useMarkingUnusableMode.ts
  beat-editor/frontend/utils/CreateChartOptions.ts
Labels: bug

#41 [DB-2] Add batch processing and enable Beat Editor within dashboard
  .gitignore
  README.md
  TODO.md
  app.py
  assets/style.css
  heartview/__init__.py
  heartview/dashboard/callbacks.py
  heartview/dashboard/layout.py
  heartview/dashboard/utils.py
  heartview/heartview.py
  heartview/pipeline/EDA.py
  heartview/pipeline/SQA.py
  requirements.txt
  setup.py
Labels: enhancement
